name: fullstack-template
version: "3.9"
services:
    fullstack-template-redis:
        container_name: fullstack-template-redis
        image: "redis:7.2.5-alpine"
        ports:
            - "127.0.0.1:4001:6379"

    fullstack-template-mongo:
        container_name: fullstack-template-mongo
        image: mongo:6.0.4
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        restart: always
        ports:
            - "127.0.0.1:4002:27017"
volumes:
    mongodb:
    mongodb_config:
